<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_eWEmkNEPEfCon65KSlHj9Q" name="MyDiagram" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_eWEmkdEPEfCon65KSlHj9Q" name="CMS(Complaint Management System)" displayName="CMS">
      <elements xmi:type="process:Lane" xmi:id="_eWEmktEPEfCon65KSlHj9Q" name="Customer" actor="_OYOoANsOEfCThLbEgJRfFQ">
        <elements xmi:type="process:ServiceTask" xmi:id="_X5vdQNHIEfCq4fAUiiAMQg" name="Notify Customer" outgoing="_mL1gMNqXEfCTLpLxFP_pPQ" incoming="_sbo-kNHJEfCq4fAUiiAMQg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_X5wrYdHIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_X5wrYNHIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_X5wrYtHIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_X5wrY9HIEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_X5wrZNHIEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_X5wrZdHIEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_X5wrZ9HIEfCq4fAUiiAMQg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_X5wrZtHIEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_-_xdkNHIEfCq4fAUiiAMQg" name="Document the case closed for reporting and close" incoming="_gkENANmzEfCuLry7pRqKVA _hZ0JQNmzEfCuLry7pRqKVA _mL1gMNqXEfCTLpLxFP_pPQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-_xdktHIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-_xdkdHIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-_xdk9HIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_eWEmk9EPEfCon65KSlHj9Q" name="Start" outgoing="_kqh2gNs8EfC71cxg3o_nxQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eWEmlNEPEfCon65KSlHj9Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eWEmldEPEfCon65KSlHj9Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eWEmltEPEfCon65KSlHj9Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ZN3qQNmtEfCuLry7pRqKVA" name=" Issue Ticket Number" outgoing="_E8HHANUoEfCluqGJMweO3w" incoming="_nuvOYNs8EfC71cxg3o_nxQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BkHfEdHIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BkHfENHIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BkHfEtHIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BkHfE9HIEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BkHfFNHIEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BkHfFdHIEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BkHfF9HIEfCq4fAUiiAMQg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BkHfFtHIEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_nUoFQNs8EfC71cxg3o_nxQ" name="Fill Form" outgoing="_nuvOYNs8EfC71cxg3o_nxQ" incoming="_kqh2gNs8EfC71cxg3o_nxQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kqTNAds8EfC71cxg3o_nxQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kqTNANs8EfC71cxg3o_nxQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kqTNAts8EfC71cxg3o_nxQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_uggdIds8EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_uggdIts8EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_uggdI9s8EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_uggdJNs8EfC71cxg3o_nxQ" name="complaintManagementInput.customerName" content="complaintManagementInput?.customerName" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_uggdJds8EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_uggdJts8EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerName">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_uggdJ9s8EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_uggdKNs8EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_uggdKds8EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_uggdKts8EfC71cxg3o_nxQ" name="complaintManagementInput.customerEmail" content="complaintManagementInput?.customerEmail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_uggdK9s8EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_uggdLNs8EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_uggdLds8EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_uggdLts8EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_uggdL9s8EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_uggdMNs8EfC71cxg3o_nxQ" name="complaintManagementInput.customerPhone" content="complaintManagementInput?.customerPhone" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_uggdMds8EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_uggdMts8EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerPhone">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_uggdM9s8EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_uggdNNs8EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_uggdNds8EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_uggdNts8EfC71cxg3o_nxQ" name="complaintManagementInput.accountNumber" content="complaintManagementInput?.accountNumber" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_uggdN9s8EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_uggdONs8EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setAccountNumber">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_uggdOds8EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_uggdOts8EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_uggdO9s8EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_uggdPNs8EfC71cxg3o_nxQ" name="complaintManagementInput.complaintType" content="complaintManagementInput?.complaintType" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_uggdPds8EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_uggdPts8EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setComplaintType">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_uggdP9s8EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_uggdQNs8EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_uggdQds8EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_uggdQts8EfC71cxg3o_nxQ" name="complaintManagementInput.description" content="complaintManagementInput?.description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_uggdQ9s8EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_uggdRNs8EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setDescription">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_uggdRds8EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_uggdRts8EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_uggdR9s8EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_uggdSNs8EfC71cxg3o_nxQ" name="complaintManagementInput.lodgmentdate" content="complaintManagementInput?.lodgmentdate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_uggdSds8EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_uggdSts8EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setLodgmentdate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kqTNA9s8EfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kqTNBNs8EfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kqTNBds8EfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kqTNB9s8EfC71cxg3o_nxQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kqTNBts8EfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_nUp6eds8EfC71cxg3o_nxQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_vZesgNs8EfC71cxg3o_nxQ" name="Customer" content="94eed787-c9e4-4f3b-b554-a9b6b43d0869" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_nUp6eNs8EfC71cxg3o_nxQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_ugdZ0Ns8EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" dataReference="complaintManagement">
              <inputs xmi:type="process:ContractInput" xmi:id="_ugdZ0ds8EfC71cxg3o_nxQ" name="customerName"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ugdZ0ts8EfC71cxg3o_nxQ" name="customerEmail"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ugdZ09s8EfC71cxg3o_nxQ" name="customerPhone" type="INTEGER"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ugdZ1Ns8EfC71cxg3o_nxQ" name="accountNumber"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ugdZ1ds8EfC71cxg3o_nxQ" name="complaintType"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ugdZ1ts8EfC71cxg3o_nxQ" name="description"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ugdZ19s8EfC71cxg3o_nxQ" name="lodgmentdate" type="LOCALDATE"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_uggdINs8EfC71cxg3o_nxQ" expression="complaintManagementInput?.accountNumber != null" errorMessage="accountNumber is mandatory for Complaint" name="mandatory_complaintManagementInput_accountNumber">
              <inputNames>complaintManagementInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_nUp6e9s8EfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_zTnXgNEPEfCon65KSlHj9Q" name="CSO" actor="_PYWoQNsOEfCThLbEgJRfFQ">
        <elements xmi:type="process:XORGateway" xmi:id="_MU3E0NHIEfCq4fAUiiAMQg" name="Resolved?" outgoing="_sbo-kNHJEfCq4fAUiiAMQg _vyJZQNs-EfC71cxg3o_nxQ" incoming="_YdW5ENUoEfCluqGJMweO3w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KIkzctHIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KIkzcdHIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KIkzc9HIEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PccSMNUoEfCluqGJMweO3w" name="First level Resolution &amp; Document Action" outgoing="_YdW5ENUoEfCluqGJMweO3w" incoming="_E8HHANUoEfCluqGJMweO3w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E8BncdUoEfCluqGJMweO3w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E8BncNUoEfCluqGJMweO3w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E8BnctUoEfCluqGJMweO3w" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_u--sYNs9EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_u--sYds9EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u--sYts9EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_u--sY9s9EfC71cxg3o_nxQ" name="complaintManagementInput.customerName" content="complaintManagementInput?.customerName" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_u--sZNs9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_u--sZds9EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerName">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_u--sZts9EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_u--sZ9s9EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u--saNs9EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_u--sads9EfC71cxg3o_nxQ" name="complaintManagementInput.customerEmail" content="complaintManagementInput?.customerEmail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_u--sats9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_u--sa9s9EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_u--sbNs9EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_u--sbds9EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u--sbts9EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_u--sb9s9EfC71cxg3o_nxQ" name="complaintManagementInput.customerPhone" content="complaintManagementInput?.customerPhone" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_u--scNs9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_u--scds9EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerPhone">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_u--scts9EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_u--sc9s9EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u--sdNs9EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_u--sdds9EfC71cxg3o_nxQ" name="complaintManagementInput.accountNumber" content="complaintManagementInput?.accountNumber" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_u--sdts9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_u--sd9s9EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setAccountNumber">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_u--seNs9EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_u--seds9EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u--sets9EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_u--se9s9EfC71cxg3o_nxQ" name="complaintManagementInput.complaintType" content="complaintManagementInput?.complaintType" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_u--sfNs9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_u--sfds9EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setComplaintType">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_u--sfts9EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_u--sf9s9EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u--sgNs9EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_u--sgds9EfC71cxg3o_nxQ" name="complaintManagementInput.description" content="complaintManagementInput?.description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_u--sgts9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_u--sg9s9EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setDescription">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_u--shNs9EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_u--shds9EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u--shts9EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_u--sh9s9EfC71cxg3o_nxQ" name="complaintManagementInput.status" content="complaintManagementInput?.status" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_u--siNs9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_u--sids9EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_u--sits9EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_u--si9s9EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u--sjNs9EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_u--sjds9EfC71cxg3o_nxQ" name="complaintManagementInput.lodgmentdate" content="complaintManagementInput?.lodgmentdate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_u--sjts9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_u--sj9s9EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setLodgmentdate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_u--skNs9EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_u--skds9EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u--skts9EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_u--sk9s9EfC71cxg3o_nxQ" name="complaintManagementInput.resolutionDetails" content="complaintManagementInput?.resolutionDetails" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_u--slNs9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_u--slds9EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setResolutionDetails">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_u--slts9EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_u--sl9s9EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u--smNs9EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_u--smds9EfC71cxg3o_nxQ" name="complaintManagementInput.resolvableAtFirstlevel" content="complaintManagementInput?.resolvableAtFirstlevel" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_u--smts9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_u--sm9s9EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setResolvableAtFirstlevel">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_E8Bnc9UoEfCluqGJMweO3w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_E8BndNUoEfCluqGJMweO3w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_E8BnddUoEfCluqGJMweO3w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_E8Bnd9UoEfCluqGJMweO3w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_E8BndtUoEfCluqGJMweO3w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PcdgWNUoEfCluqGJMweO3w">
            <targetForm xmi:type="expression:Expression" xmi:id="_x1wsQNs9EfC71cxg3o_nxQ" name="firstLevel" content="4b92a92c-4d5d-4ef0-8161-b183aac5b8e6" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PcdgV9UoEfCluqGJMweO3w">
            <inputs xmi:type="process:ContractInput" xmi:id="_u--FUNs9EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" dataReference="complaintManagement" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_u--FUds9EfC71cxg3o_nxQ" name="customerName" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_u--FUts9EfC71cxg3o_nxQ" name="customerEmail" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_u--FU9s9EfC71cxg3o_nxQ" name="customerPhone" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_u--FVNs9EfC71cxg3o_nxQ" name="accountNumber" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_u--FVds9EfC71cxg3o_nxQ" name="complaintType" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_u--FVts9EfC71cxg3o_nxQ" name="description" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_u--FV9s9EfC71cxg3o_nxQ" name="status" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_u--FWNs9EfC71cxg3o_nxQ" name="lodgmentdate" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_u--FWds9EfC71cxg3o_nxQ" name="resolutionDetails" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_u--FWts9EfC71cxg3o_nxQ" name="resolvableAtFirstlevel" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_u--FW9s9EfC71cxg3o_nxQ" expression="complaintManagementInput?.accountNumber != null" errorMessage="accountNumber is mandatory for Complaint" name="mandatory_complaintManagementInput_accountNumber">
              <inputNames>complaintManagementInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PcdgWtUoEfCluqGJMweO3w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_wJh-gNs-EfC71cxg3o_nxQ" name="Escalate To CMO" outgoing="_ly9E4NtBEfC71cxg3o_nxQ" incoming="_vyJZQNs-EfC71cxg3o_nxQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vyHkEds-EfC71cxg3o_nxQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vyHkENs-EfC71cxg3o_nxQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vyHkEts-EfC71cxg3o_nxQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_8nq6Ots-EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8nq6O9s-EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8nq6PNs-EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8nq6Pds-EfC71cxg3o_nxQ" name="complaintManagementInput.customerName" content="complaintManagementInput?.customerName" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8nq6Pts-EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8nq6P9s-EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerName">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8nq6QNs-EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8nq6Qds-EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8nq6Qts-EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8nq6Q9s-EfC71cxg3o_nxQ" name="complaintManagementInput.customerEmail" content="complaintManagementInput?.customerEmail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8nq6RNs-EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8nq6Rds-EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8nq6Rts-EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8nq6R9s-EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8nq6SNs-EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8nq6Sds-EfC71cxg3o_nxQ" name="complaintManagementInput.customerPhone" content="complaintManagementInput?.customerPhone" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8nq6Sts-EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8nq6S9s-EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerPhone">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8nq6TNs-EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8nq6Tds-EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8nq6Tts-EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8nq6T9s-EfC71cxg3o_nxQ" name="complaintManagementInput.accountNumber" content="complaintManagementInput?.accountNumber" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8nq6UNs-EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8nq6Uds-EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setAccountNumber">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8nq6Uts-EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8nq6U9s-EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8nq6VNs-EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8nq6Vds-EfC71cxg3o_nxQ" name="complaintManagementInput.complaintType" content="complaintManagementInput?.complaintType" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8nq6Vts-EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8nq6V9s-EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setComplaintType">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8nq6WNs-EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8nq6Wds-EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8nq6Wts-EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8nq6W9s-EfC71cxg3o_nxQ" name="complaintManagementInput.description" content="complaintManagementInput?.description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8nq6XNs-EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8nq6Xds-EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setDescription">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8nq6Xts-EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8nq6X9s-EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8nq6YNs-EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8nq6Yds-EfC71cxg3o_nxQ" name="complaintManagementInput.status" content="complaintManagementInput?.status" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8nq6Yts-EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8nq6Y9s-EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8nq6ZNs-EfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8nq6Zds-EfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8nq6Zts-EfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8nq6Z9s-EfC71cxg3o_nxQ" name="complaintManagementInput.lodgmentdate" content="complaintManagementInput?.lodgmentdate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8nq6aNs-EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8nq6ads-EfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setLodgmentdate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_vyHkE9s-EfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_vyHkFNs-EfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_vyHkFds-EfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_vyHkF9s-EfC71cxg3o_nxQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_vyHkFts-EfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_wJilmds-EfC71cxg3o_nxQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_91JZ8Ns-EfC71cxg3o_nxQ" name="Escalate" content="af686ce7-7fcd-4052-99d9-451a8d3f96ef" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_wJilmNs-EfC71cxg3o_nxQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_8nq6MNs-EfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" dataReference="complaintManagement" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_8nq6Mds-EfC71cxg3o_nxQ" name="customerName" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_8nq6Mts-EfC71cxg3o_nxQ" name="customerEmail" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_8nq6M9s-EfC71cxg3o_nxQ" name="customerPhone" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_8nq6NNs-EfC71cxg3o_nxQ" name="accountNumber" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_8nq6Nds-EfC71cxg3o_nxQ" name="complaintType" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_8nq6Nts-EfC71cxg3o_nxQ" name="description" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_8nq6N9s-EfC71cxg3o_nxQ" name="status" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_8nq6ONs-EfC71cxg3o_nxQ" name="lodgmentdate" type="LOCALDATE" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_8nq6Ods-EfC71cxg3o_nxQ" expression="complaintManagementInput?.accountNumber != null" errorMessage="accountNumber is mandatory for Complaint" name="mandatory_complaintManagementInput_accountNumber">
              <inputNames>complaintManagementInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_wJilm9s-EfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_kZUF8NEQEfCon65KSlHj9Q" name="CMO" actor="_P-0LUNsOEfCThLbEgJRfFQ">
        <elements xmi:type="process:XORGateway" xmi:id="_f26I4NmvEfCuLry7pRqKVA" name="Investigation Required ?" outgoing="_Z3pfsNmwEfCuLry7pRqKVA _tv2ZOdmwEfCuLry7pRqKVA" incoming="_3WRewNtOEfCjh-E5DQ7z2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fZz9MdmvEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fZz9MNmvEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fZz9MtmvEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_tv0kANmwEfCuLry7pRqKVA" name="Assign to the respective department" outgoing="_tAcwENtyEfCjh-E5DQ7z2A" incoming="_tv2ZOdmwEfCuLry7pRqKVA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tv1yIdmwEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tv1yINmwEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tv2ZMNmwEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tv2ZMdmwEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tv2ZMtmwEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tv2ZM9mwEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tv2ZNdmwEfCuLry7pRqKVA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tv2ZNNmwEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_eEiMcNqYEfCTLpLxFP_pPQ" name="Notify CMM" outgoing="_rxaMIdqYEfCTLpLxFP_pPQ" incoming="_tXHZ4NtBEfC71cxg3o_nxQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eEl20dqYEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eEl20NqYEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eEl20tqYEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_eEl209qYEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_eEl21NqYEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_eEl21dqYEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_eEl219qYEfCTLpLxFP_pPQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_eEl21tqYEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_rxXv4NqYEfCTLpLxFP_pPQ" name="End1" incoming="_rxaMIdqYEfCTLpLxFP_pPQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rxY-AdqYEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rxY-ANqYEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rxY-AtqYEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_pnGE4NtBEfC71cxg3o_nxQ" name="screens the complaint and sets its priority level and categorize" outgoing="_3WRewNtOEfCjh-E5DQ7z2A" incoming="_ly9E4NtBEfC71cxg3o_nxQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ly72wttBEfC71cxg3o_nxQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ly72wdtBEfC71cxg3o_nxQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ly72w9tBEfC71cxg3o_nxQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_IuieDNtCEfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IuieDdtCEfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IuieDttCEfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IuieD9tCEfC71cxg3o_nxQ" name="complaintManagementInput.customerName" content="complaintManagementInput?.customerName" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IuieENtCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IuieEdtCEfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerName">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IuieEttCEfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IuieE9tCEfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IuieFNtCEfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IuieFdtCEfC71cxg3o_nxQ" name="complaintManagementInput.customerEmail" content="complaintManagementInput?.customerEmail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IuieFttCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IuieF9tCEfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IuieGNtCEfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IuieGdtCEfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IuieGttCEfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IuieG9tCEfC71cxg3o_nxQ" name="complaintManagementInput.customerPhone" content="complaintManagementInput?.customerPhone" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IuieHNtCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IuieHdtCEfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setCustomerPhone">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IuieHttCEfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IuieH9tCEfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IuieINtCEfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IuieIdtCEfC71cxg3o_nxQ" name="complaintManagementInput.accountNumber" content="complaintManagementInput?.accountNumber" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IuieIttCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IuieI9tCEfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setAccountNumber">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IuieJNtCEfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IuieJdtCEfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IuieJttCEfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IuieJ9tCEfC71cxg3o_nxQ" name="complaintManagementInput.complaintType" content="complaintManagementInput?.complaintType" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IuieKNtCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IuieKdtCEfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setComplaintType">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IuieKttCEfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IuieK9tCEfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IuieLNtCEfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IuieLdtCEfC71cxg3o_nxQ" name="complaintManagementInput.priority" content="complaintManagementInput?.priority" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IuieLttCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IuieL9tCEfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setPriority">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IuieMNtCEfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IuieMdtCEfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IuieMttCEfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IuieM9tCEfC71cxg3o_nxQ" name="complaintManagementInput.description" content="complaintManagementInput?.description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IuieNNtCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IuieNdtCEfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setDescription">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IuieNttCEfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IuieN9tCEfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IuieONtCEfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IuieOdtCEfC71cxg3o_nxQ" name="complaintManagementInput.status" content="complaintManagementInput?.status" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IuieOttCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IuieO9tCEfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IuiePNtCEfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IuiePdtCEfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IuiePttCEfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IuieP9tCEfC71cxg3o_nxQ" name="complaintManagementInput.lodgmentdate" content="complaintManagementInput?.lodgmentdate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IuieQNtCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IuieQdtCEfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setLodgmentdate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IuieQttCEfC71cxg3o_nxQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IuieQ9tCEfC71cxg3o_nxQ" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IuieRNtCEfC71cxg3o_nxQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IuieRdtCEfC71cxg3o_nxQ" name="complaintManagementInput.subCategory" content="complaintManagementInput?.subCategory" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IuieRttCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IuieR9tCEfC71cxg3o_nxQ" type="JAVA_METHOD" expression="setSubCategory">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ly72xNtBEfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ly72xdtBEfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ly72xttBEfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ly72yNtBEfC71cxg3o_nxQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ly72x9tBEfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_rlfrQNtBEfC71cxg3o_nxQ" name="SLA FOR CMO" outgoing="_tXHZ4NtBEfC71cxg3o_nxQ">
            <condition xmi:type="expression:Expression" xmi:id="_uNgPUNtBEfC71cxg3o_nxQ" name="newScript()" content="sla_screening" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:Data" xmi:id="_x53zYNtBEfC71cxg3o_nxQ" name="sla_screening" dataType="_eWEmv9EPEfCon65KSlHj9Q"/>
            </condition>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pnGr-dtBEfC71cxg3o_nxQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_J71-oNtCEfC71cxg3o_nxQ" name="sccreenCMO" content="972e9354-2bcb-4359-87f2-0e0e22fadf4f" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pnGr-NtBEfC71cxg3o_nxQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_IuieANtCEfC71cxg3o_nxQ" name="complaintManagementInput" type="COMPLEX" dataReference="complaintManagement" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_IuieAdtCEfC71cxg3o_nxQ" name="customerName" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IuieAttCEfC71cxg3o_nxQ" name="customerEmail" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IuieA9tCEfC71cxg3o_nxQ" name="customerPhone" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IuieBNtCEfC71cxg3o_nxQ" name="accountNumber" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IuieBdtCEfC71cxg3o_nxQ" name="complaintType" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IuieBttCEfC71cxg3o_nxQ" name="priority" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IuieB9tCEfC71cxg3o_nxQ" name="description" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IuieCNtCEfC71cxg3o_nxQ" name="status" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IuieCdtCEfC71cxg3o_nxQ" name="lodgmentdate" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IuieCttCEfC71cxg3o_nxQ" name="subCategory" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_IuieC9tCEfC71cxg3o_nxQ" expression="complaintManagementInput?.accountNumber != null" errorMessage="accountNumber is mandatory for Complaint" name="mandatory_complaintManagementInput_accountNumber">
              <inputNames>complaintManagementInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_pnGr-9tBEfC71cxg3o_nxQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_j17sENEQEfCon65KSlHj9Q" name="Audit Department" actor="_RuKpENsOEfCThLbEgJRfFQ">
        <elements xmi:type="process:Task" xmi:id="_VcDA4NHKEfCq4fAUiiAMQg" name="Undertake Investigation and pass decision " outgoing="_lf0QMdtyEfCjh-E5DQ7z2A" incoming="_Z3pfsNmwEfCuLry7pRqKVA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VcDn8NHKEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VcDA4dHKEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VcDn8dHKEfCq4fAUiiAMQg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_iD21wdtpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD21wttpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD21w9tpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD21xNtpEfCjh-E5DQ7z2A" name="complaintManagementInput.customerName" content="complaintManagementInput?.customerName" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD21xdtpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD21xttpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setCustomerName">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD21x9tpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD21yNtpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD21ydtpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD21yttpEfCjh-E5DQ7z2A" name="complaintManagementInput.customerEmail" content="complaintManagementInput?.customerEmail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD21y9tpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD21zNtpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setCustomerEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD21zdtpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD21zttpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD21z9tpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD210NtpEfCjh-E5DQ7z2A" name="complaintManagementInput.customerPhone" content="complaintManagementInput?.customerPhone" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD210dtpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD210ttpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setCustomerPhone">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD2109tpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD211NtpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD211dtpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD211ttpEfCjh-E5DQ7z2A" name="complaintManagementInput.accountNumber" content="complaintManagementInput?.accountNumber" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD2119tpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD212NtpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setAccountNumber">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD212dtpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD212ttpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD2129tpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD213NtpEfCjh-E5DQ7z2A" name="complaintManagementInput.complaintType" content="complaintManagementInput?.complaintType" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD213dtpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD213ttpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setComplaintType">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD2139tpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD214NtpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD214dtpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD214ttpEfCjh-E5DQ7z2A" name="complaintManagementInput.priority" content="complaintManagementInput?.priority" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD2149tpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD215NtpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setPriority">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD215dtpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD215ttpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD2159tpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD216NtpEfCjh-E5DQ7z2A" name="complaintManagementInput.description" content="complaintManagementInput?.description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD216dtpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD216ttpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setDescription">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD2169tpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD217NtpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD217dtpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD217ttpEfCjh-E5DQ7z2A" name="complaintManagementInput.status" content="complaintManagementInput?.status" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD2179tpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD218NtpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD218dtpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD218ttpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD2189tpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD219NtpEfCjh-E5DQ7z2A" name="complaintManagementInput.lodgmentdate" content="complaintManagementInput?.lodgmentdate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD219dtpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD219ttpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setLodgmentdate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD2199tpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD21-NtpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD21-dtpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD21-ttpEfCjh-E5DQ7z2A" name="complaintManagementInput.assignedTo" content="complaintManagementInput?.assignedTo" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD21-9tpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD21_NtpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setAssignedTo">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD21_dtpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD21_ttpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD21_9tpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD22ANtpEfCjh-E5DQ7z2A" name="complaintManagementInput.subCategory" content="complaintManagementInput?.subCategory" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD22AdtpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD22AttpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setSubCategory">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD22A9tpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD22BNtpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD22BdtpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD22BttpEfCjh-E5DQ7z2A" name="complaintManagementInput.investigationMethod" content="complaintManagementInput?.investigationMethod" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD22B9tpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD22CNtpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setInvestigationMethod">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD22CdtpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD22CttpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD22C9tpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD22DNtpEfCjh-E5DQ7z2A" name="complaintManagementInput.findingsSummary" content="complaintManagementInput?.findingsSummary" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD22DdtpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD22DttpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setFindingsSummary">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_iD22D9tpEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_iD22ENtpEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_iD22EdtpEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_iD22EttpEfCjh-E5DQ7z2A" name="complaintManagementInput.decisionBy" content="complaintManagementInput?.decisionBy" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_iD22E9tpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_iD22FNtpEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setDecisionBy">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VcDn8tHKEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VcDn89HKEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VcDn9NHKEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VcDn9tHKEfCq4fAUiiAMQg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VcDn9dHKEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_2qrbwNqYEfCTLpLxFP_pPQ" name="SLA for Investigation" outgoing="__WsJoNqYEfCTLpLxFP_pPQ">
            <condition xmi:type="expression:Expression" xmi:id="_pSXhYNqZEfCTLpLxFP_pPQ" name="newScript()" content="sla_investigation" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:Data" xmi:id="_t57iYNqZEfCTLpLxFP_pPQ" name="sla_investigation" dataType="_eWEmv9EPEfCon65KSlHj9Q"/>
            </condition>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_VcDn-NHKEfCq4fAUiiAMQg">
            <targetForm xmi:type="expression:Expression" xmi:id="_kLJ5cNtpEfCjh-E5DQ7z2A" name="investigation" content="e0041250-3500-4549-b8c8-fc811e31608e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_VcDn99HKEfCq4fAUiiAMQg">
            <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZgNtpEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" dataReference="complaintManagement" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZgdtpEfCjh-E5DQ7z2A" name="customerName" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZgttpEfCjh-E5DQ7z2A" name="customerEmail" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0Zg9tpEfCjh-E5DQ7z2A" name="customerPhone" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZhNtpEfCjh-E5DQ7z2A" name="accountNumber" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZhdtpEfCjh-E5DQ7z2A" name="complaintType" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZhttpEfCjh-E5DQ7z2A" name="priority" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0Zh9tpEfCjh-E5DQ7z2A" name="description" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZiNtpEfCjh-E5DQ7z2A" name="status" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZidtpEfCjh-E5DQ7z2A" name="lodgmentdate" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZittpEfCjh-E5DQ7z2A" name="assignedTo" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0Zi9tpEfCjh-E5DQ7z2A" name="subCategory" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZjNtpEfCjh-E5DQ7z2A" name="investigationMethod" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZjdtpEfCjh-E5DQ7z2A" name="findingsSummary" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_iD0ZjttpEfCjh-E5DQ7z2A" name="decisionBy" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_iD21wNtpEfCjh-E5DQ7z2A" expression="complaintManagementInput?.accountNumber != null" errorMessage="accountNumber is mandatory for Complaint" name="mandatory_complaintManagementInput_accountNumber">
              <inputNames>complaintManagementInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_VcDn-tHKEfCq4fAUiiAMQg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="__WqUcNqYEfCTLpLxFP_pPQ" name="Notify Audit Department" outgoing="_Iuj38NqZEfCTLpLxFP_pPQ" incoming="__WsJoNqYEfCTLpLxFP_pPQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__Wq7gdqYEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__Wq7gNqYEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__Wq7gtqYEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__Wq7g9qYEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__Wq7hNqYEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__Wq7hdqYEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__Wq7h9qYEfCTLpLxFP_pPQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__Wq7htqYEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_IuiCwNqZEfCTLpLxFP_pPQ" name="End2" incoming="_Iuj38NqZEfCTLpLxFP_pPQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Iuip0dqZEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Iuip0NqZEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Iuip0tqZEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_krRaUNmwEfCuLry7pRqKVA" name="Department" actor="_TOo9UNsOEfCThLbEgJRfFQ">
        <elements xmi:type="process:XORGateway" xmi:id="_Por74NmxEfCuLry7pRqKVA" name="Sensetive" outgoing="_znLHAtmyEfCuLry7pRqKVA _02fZ3NmyEfCuLry7pRqKVA" incoming="_rAGB4NtyEfCjh-E5DQ7z2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PQrrkNmxEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PQrEgNmxEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PQrrkdmxEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_02fZ0NmyEfCuLry7pRqKVA" name="Notified by CMM" outgoing="_hZ0JQNmzEfCuLry7pRqKVA" incoming="_02fZ3NmyEfCuLry7pRqKVA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_02fZ0tmyEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_02fZ0dmyEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_02fZ09myEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_02fZ1NmyEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_02fZ1dmyEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_02fZ1tmyEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_02fZ2NmyEfCuLry7pRqKVA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_02fZ19myEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ZoPx4NqZEfCTLpLxFP_pPQ" name="Notify Department" outgoing="_ci92lNqZEfCTLpLxFP_pPQ" incoming="_48g5cNtyEfCjh-E5DQ7z2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZoQY8dqZEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZoQY8NqZEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZoQY8tqZEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZoQY89qZEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZoQY9NqZEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZoQY9dqZEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZoQY99qZEfCTLpLxFP_pPQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZoQY9tqZEfCTLpLxFP_pPQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_ci9PgNqZEfCTLpLxFP_pPQ" name="End3" incoming="_ci92lNqZEfCTLpLxFP_pPQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ci9PgtqZEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ci9PgdqZEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ci9Pg9qZEfCTLpLxFP_pPQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_qX8cwNtyEfCjh-E5DQ7z2A" name="Second level resolution" outgoing="_rAGB4NtyEfCjh-E5DQ7z2A" incoming="_lf0QMdtyEfCjh-E5DQ7z2A _tAcwENtyEfCjh-E5DQ7z2A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lfzpIdtyEfCjh-E5DQ7z2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lfzpINtyEfCjh-E5DQ7z2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lfzpIttyEfCjh-E5DQ7z2A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxkdtzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxkttzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxk9tzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRxlNtzEfCjh-E5DQ7z2A" name="complaintManagementInput.customerName" content="complaintManagementInput?.customerName" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRxldtzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRxlttzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setCustomerName">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxl9tzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxmNtzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxmdtzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRxmttzEfCjh-E5DQ7z2A" name="complaintManagementInput.customerEmail" content="complaintManagementInput?.customerEmail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRxm9tzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRxnNtzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setCustomerEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxndtzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxnttzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxn9tzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRxoNtzEfCjh-E5DQ7z2A" name="complaintManagementInput.customerPhone" content="complaintManagementInput?.customerPhone" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRxodtzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRxottzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setCustomerPhone">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxo9tzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxpNtzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxpdtzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRxpttzEfCjh-E5DQ7z2A" name="complaintManagementInput.accountNumber" content="complaintManagementInput?.accountNumber" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRxp9tzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRxqNtzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setAccountNumber">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxqdtzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxqttzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxq9tzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRxrNtzEfCjh-E5DQ7z2A" name="complaintManagementInput.complaintType" content="complaintManagementInput?.complaintType" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRxrdtzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRxrttzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setComplaintType">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxr9tzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxsNtzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxsdtzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRxsttzEfCjh-E5DQ7z2A" name="complaintManagementInput.priority" content="complaintManagementInput?.priority" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRxs9tzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRxtNtzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setPriority">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxtdtzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxtttzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxt9tzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRxuNtzEfCjh-E5DQ7z2A" name="complaintManagementInput.description" content="complaintManagementInput?.description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRxudtzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRxuttzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setDescription">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxu9tzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxvNtzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxvdtzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRxvttzEfCjh-E5DQ7z2A" name="complaintManagementInput.status" content="complaintManagementInput?.status" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRxv9tzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRxwNtzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxwdtzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxwttzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxw9tzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRxxNtzEfCjh-E5DQ7z2A" name="complaintManagementInput.lodgmentdate" content="complaintManagementInput?.lodgmentdate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRxxdtzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRxxttzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setLodgmentdate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxx9tzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxyNtzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxydtzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRxyttzEfCjh-E5DQ7z2A" name="complaintManagementInput.resolutionDetails" content="complaintManagementInput?.resolutionDetails" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRxy9tzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRxzNtzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setResolutionDetails">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRxzdtzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRxzttzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRxz9tzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRx0NtzEfCjh-E5DQ7z2A" name="complaintManagementInput.subCategory" content="complaintManagementInput?.subCategory" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRx0dtzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRx0ttzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setSubCategory">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRx09tzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRx1NtzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRx1dtzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRx1ttzEfCjh-E5DQ7z2A" name="complaintManagementInput.complaintId" content="complaintManagementInput?.complaintId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRx19tzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRx2NtzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setComplaintId">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRx2dtzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRx2ttzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRx29tzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRx3NtzEfCjh-E5DQ7z2A" name="complaintManagementInput.resolvedBy" content="complaintManagementInput?.resolvedBy" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRx3dtzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRx3ttzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setResolvedBy">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JwRx39tzEfCjh-E5DQ7z2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JwRx4NtzEfCjh-E5DQ7z2A" name="complaintManagement" content="complaintManagement" type="TYPE_VARIABLE" returnType="com.company.model.Complaint">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JwRx4dtzEfCjh-E5DQ7z2A" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JwRx4ttzEfCjh-E5DQ7z2A" name="complaintManagementInput.rootCause" content="complaintManagementInput?.rootCause" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JwRx49tzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JwRx5NtzEfCjh-E5DQ7z2A" type="JAVA_METHOD" expression="setRootCause">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lfzpI9tyEfCjh-E5DQ7z2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lfzpJNtyEfCjh-E5DQ7z2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lfzpJdtyEfCjh-E5DQ7z2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lfzpJ9tyEfCjh-E5DQ7z2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lfzpJttyEfCjh-E5DQ7z2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_1s1RYNtyEfCjh-E5DQ7z2A" name="SLA for second level resolution" outgoing="_48g5cNtyEfCjh-E5DQ7z2A">
            <condition xmi:type="expression:Expression" xmi:id="_7T2kQNtyEfCjh-E5DQ7z2A" name="newScript()" content="sla_second_level" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:Data" xmi:id="_9odEINtyEfCjh-E5DQ7z2A" name="sla_second_level" dataType="_eWEmv9EPEfCon65KSlHj9Q"/>
            </condition>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_qX9q6dtyEfCjh-E5DQ7z2A">
            <targetForm xmi:type="expression:Expression" xmi:id="_LG4_MNtzEfCjh-E5DQ7z2A" name="secondLevel4" content="3498a65e-dc18-408f-b95b-2932caaa2d22" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_qX9q6NtyEfCjh-E5DQ7z2A">
            <inputs xmi:type="process:ContractInput" xmi:id="_JwRKgNtzEfCjh-E5DQ7z2A" name="complaintManagementInput" type="COMPLEX" dataReference="complaintManagement" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKgdtzEfCjh-E5DQ7z2A" name="customerName" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKgttzEfCjh-E5DQ7z2A" name="customerEmail" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKg9tzEfCjh-E5DQ7z2A" name="customerPhone" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKhNtzEfCjh-E5DQ7z2A" name="accountNumber" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKhdtzEfCjh-E5DQ7z2A" name="complaintType" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKhttzEfCjh-E5DQ7z2A" name="priority" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKh9tzEfCjh-E5DQ7z2A" name="description" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKiNtzEfCjh-E5DQ7z2A" name="status" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKidtzEfCjh-E5DQ7z2A" name="lodgmentdate" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKittzEfCjh-E5DQ7z2A" name="resolutionDetails" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKi9tzEfCjh-E5DQ7z2A" name="subCategory" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKjNtzEfCjh-E5DQ7z2A" name="complaintId" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKjdtzEfCjh-E5DQ7z2A" name="resolvedBy" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JwRKjttzEfCjh-E5DQ7z2A" name="rootCause" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_JwRxkNtzEfCjh-E5DQ7z2A" expression="complaintManagementInput?.accountNumber != null" errorMessage="accountNumber is mandatory for Complaint" name="mandatory_complaintManagementInput_accountNumber">
              <inputNames>complaintManagementInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_qX9q69tyEfCjh-E5DQ7z2A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_DmUm0NsdEfCThLbEgJRfFQ" name="SQD" actor="_pQdlYNt0EfCjh-E5DQ7z2A">
        <elements xmi:type="process:ServiceTask" xmi:id="_znJ44NmyEfCuLry7pRqKVA" name="Notified by SQD" outgoing="_gkENANmzEfCuLry7pRqKVA" incoming="_znLHAtmyEfCuLry7pRqKVA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_znKf8dmyEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_znKf8NmyEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_znKf8tmyEfCuLry7pRqKVA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_znKf89myEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_znKf9NmyEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_znKf9dmyEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_znKf99myEfCuLry7pRqKVA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_znKf9tmyEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_M0tDYNqYEfCTLpLxFP_pPQ" name="sla_screening" dataType="_eWEmv9EPEfCon65KSlHj9Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_M0tDYdqYEfCTLpLxFP_pPQ" name="172800" content="172800" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_QS5BgNqYEfCTLpLxFP_pPQ" name="sla_first_level" dataType="_eWEmv9EPEfCon65KSlHj9Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_QS5BgdqYEfCTLpLxFP_pPQ" name="172800" content="172800" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_TtFQcNqYEfCTLpLxFP_pPQ" name="sla_second_level" dataType="_eWEmv9EPEfCon65KSlHj9Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_TtF3gNqYEfCTLpLxFP_pPQ" name="259200" content="259200" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_XF60gNqYEfCTLpLxFP_pPQ" name="sla_investigation" dataType="_eWEmv9EPEfCon65KSlHj9Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_XF60gdqYEfCTLpLxFP_pPQ" name="432000" content="432000" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_xRL8oNqaEfCTLpLxFP_pPQ" name="isResolved" dataType="_eWEmvNEPEfCon65KSlHj9Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_xRMjsNqaEfCTLpLxFP_pPQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_0V8HENqaEfCTLpLxFP_pPQ" name="investigationRequired" dataType="_eWEmvNEPEfCon65KSlHj9Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_0V8HEdqaEfCTLpLxFP_pPQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_1VHsINqaEfCTLpLxFP_pPQ" name="sensetive" dataType="_eWEmvNEPEfCon65KSlHj9Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_1VHsIdqaEfCTLpLxFP_pPQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_0JaJsNsYEfCThLbEgJRfFQ" name="complaintManagement" dataType="_eWEmxNEPEfCon65KSlHj9Q" className="com.company.model.Complaint">
        <defaultValue xmi:type="expression:Expression" xmi:id="_0JawwNsYEfCThLbEgJRfFQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_eWEmpNEPEfCon65KSlHj9Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_lrLQ4NqcEfCTLpLxFP_pPQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_eWEmptEPEfCon65KSlHj9Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_eWEmp9EPEfCon65KSlHj9Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sbo-kNHJEfCq4fAUiiAMQg" name="Yes" target="_X5vdQNHIEfCq4fAUiiAMQg" source="_MU3E0NHIEfCq4fAUiiAMQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sbploNHJEfCq4fAUiiAMQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_sbplodHJEfCq4fAUiiAMQg" name="newScript()" content="isResolved.TRUE" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_9QEJcNqaEfCTLpLxFP_pPQ" name="isResolved" dataType="_eWEmvNEPEfCon65KSlHj9Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E8HHANUoEfCluqGJMweO3w" target="_PccSMNUoEfCluqGJMweO3w" source="_ZN3qQNmtEfCuLry7pRqKVA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E8HuENUoEfCluqGJMweO3w"/>
        <condition xmi:type="expression:Expression" xmi:id="_E8HuEdUoEfCluqGJMweO3w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YdW5ENUoEfCluqGJMweO3w" target="_MU3E0NHIEfCq4fAUiiAMQg" source="_PccSMNUoEfCluqGJMweO3w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YdW5EdUoEfCluqGJMweO3w"/>
        <condition xmi:type="expression:Expression" xmi:id="_YdXgINUoEfCluqGJMweO3w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Z3pfsNmwEfCuLry7pRqKVA" name="No" target="_VcDA4NHKEfCq4fAUiiAMQg" source="_f26I4NmvEfCuLry7pRqKVA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Z3qGwNmwEfCuLry7pRqKVA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Z3qGwdmwEfCuLry7pRqKVA" name="newScript()" content="investigationRequired.FALSE" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_33CZ0NqbEfCTLpLxFP_pPQ" name="investigationRequired" dataType="_eWEmvNEPEfCon65KSlHj9Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tv2ZOdmwEfCuLry7pRqKVA" name="Yes" target="_tv0kANmwEfCuLry7pRqKVA" source="_f26I4NmvEfCuLry7pRqKVA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tv2ZOtmwEfCuLry7pRqKVA"/>
        <condition xmi:type="expression:Expression" xmi:id="_tv2ZO9mwEfCuLry7pRqKVA" name="newScript()" content="investigationRequired.TRUE" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_1XdZANqbEfCTLpLxFP_pPQ" name="investigationRequired" dataType="_eWEmvNEPEfCon65KSlHj9Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_znLHAtmyEfCuLry7pRqKVA" name="Yes" target="_znJ44NmyEfCuLry7pRqKVA" source="_Por74NmxEfCuLry7pRqKVA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_znLHA9myEfCuLry7pRqKVA"/>
        <condition xmi:type="expression:Expression" xmi:id="_znLHBNmyEfCuLry7pRqKVA" name="newScript()" content="sensetive.TRUE" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_R38-ANqcEfCTLpLxFP_pPQ" name="sensetive" dataType="_eWEmvNEPEfCon65KSlHj9Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_02fZ3NmyEfCuLry7pRqKVA" name="No" target="_02fZ0NmyEfCuLry7pRqKVA" source="_Por74NmxEfCuLry7pRqKVA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_02fZ3dmyEfCuLry7pRqKVA"/>
        <condition xmi:type="expression:Expression" xmi:id="_02fZ3tmyEfCuLry7pRqKVA" name="newScript()" content="sensetive.FALSE" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_Uq9RINqcEfCTLpLxFP_pPQ" name="sensetive" dataType="_eWEmvNEPEfCon65KSlHj9Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gkENANmzEfCuLry7pRqKVA" target="_-_xdkNHIEfCq4fAUiiAMQg" source="_znJ44NmyEfCuLry7pRqKVA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gkE0ENmzEfCuLry7pRqKVA"/>
        <condition xmi:type="expression:Expression" xmi:id="_gkE0EdmzEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hZ0JQNmzEfCuLry7pRqKVA" target="_-_xdkNHIEfCq4fAUiiAMQg" source="_02fZ0NmyEfCuLry7pRqKVA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hZ0JQdmzEfCuLry7pRqKVA"/>
        <condition xmi:type="expression:Expression" xmi:id="_hZ0JQtmzEfCuLry7pRqKVA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mL1gMNqXEfCTLpLxFP_pPQ" target="_-_xdkNHIEfCq4fAUiiAMQg" source="_X5vdQNHIEfCq4fAUiiAMQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mMEwwNqXEfCTLpLxFP_pPQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_mMF-4NqXEfCTLpLxFP_pPQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rxaMIdqYEfCTLpLxFP_pPQ" target="_rxXv4NqYEfCTLpLxFP_pPQ" source="_eEiMcNqYEfCTLpLxFP_pPQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rxaMItqYEfCTLpLxFP_pPQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_rxazMNqYEfCTLpLxFP_pPQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__WsJoNqYEfCTLpLxFP_pPQ" target="__WqUcNqYEfCTLpLxFP_pPQ" source="_2qrbwNqYEfCTLpLxFP_pPQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__WsJodqYEfCTLpLxFP_pPQ"/>
        <condition xmi:type="expression:Expression" xmi:id="__WsJotqYEfCTLpLxFP_pPQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Iuj38NqZEfCTLpLxFP_pPQ" target="_IuiCwNqZEfCTLpLxFP_pPQ" source="__WqUcNqYEfCTLpLxFP_pPQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Iuj38dqZEfCTLpLxFP_pPQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Iuj38tqZEfCTLpLxFP_pPQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ci92lNqZEfCTLpLxFP_pPQ" target="_ci9PgNqZEfCTLpLxFP_pPQ" source="_ZoPx4NqZEfCTLpLxFP_pPQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ci-doNqZEfCTLpLxFP_pPQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ci-dodqZEfCTLpLxFP_pPQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kqh2gNs8EfC71cxg3o_nxQ" target="_nUoFQNs8EfC71cxg3o_nxQ" source="_eWEmk9EPEfCon65KSlHj9Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kqidkNs8EfC71cxg3o_nxQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kqidkds8EfC71cxg3o_nxQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nuvOYNs8EfC71cxg3o_nxQ" target="_ZN3qQNmtEfCuLry7pRqKVA" source="_nUoFQNs8EfC71cxg3o_nxQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nuwcgNs8EfC71cxg3o_nxQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_nuwcgds8EfC71cxg3o_nxQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vyJZQNs-EfC71cxg3o_nxQ" name="No" target="_wJh-gNs-EfC71cxg3o_nxQ" source="_MU3E0NHIEfCq4fAUiiAMQg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vyKAUNs-EfC71cxg3o_nxQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_vyKAUds-EfC71cxg3o_nxQ" name="newScript()" content="isResolved.FALSE" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_2qS80Ns-EfC71cxg3o_nxQ" name="isResolved" dataType="_eWEmvNEPEfCon65KSlHj9Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ly9E4NtBEfC71cxg3o_nxQ" target="_pnGE4NtBEfC71cxg3o_nxQ" source="_wJh-gNs-EfC71cxg3o_nxQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ly9E4dtBEfC71cxg3o_nxQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ly9E4ttBEfC71cxg3o_nxQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tXHZ4NtBEfC71cxg3o_nxQ" target="_eEiMcNqYEfCTLpLxFP_pPQ" source="_rlfrQNtBEfC71cxg3o_nxQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tXHZ4dtBEfC71cxg3o_nxQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_tXHZ4ttBEfC71cxg3o_nxQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3WRewNtOEfCjh-E5DQ7z2A" target="_f26I4NmvEfCuLry7pRqKVA" source="_pnGE4NtBEfC71cxg3o_nxQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3WuKsNtOEfCjh-E5DQ7z2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_3WuKsdtOEfCjh-E5DQ7z2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lf0QMdtyEfCjh-E5DQ7z2A" target="_qX8cwNtyEfCjh-E5DQ7z2A" source="_VcDA4NHKEfCq4fAUiiAMQg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lf03QNtyEfCjh-E5DQ7z2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_lf03QdtyEfCjh-E5DQ7z2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rAGB4NtyEfCjh-E5DQ7z2A" target="_Por74NmxEfCuLry7pRqKVA" source="_qX8cwNtyEfCjh-E5DQ7z2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rAGB4dtyEfCjh-E5DQ7z2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_rAGB4ttyEfCjh-E5DQ7z2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tAcwENtyEfCjh-E5DQ7z2A" target="_qX8cwNtyEfCjh-E5DQ7z2A" source="_tv0kANmwEfCuLry7pRqKVA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tAcwEdtyEfCjh-E5DQ7z2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_tAcwEttyEfCjh-E5DQ7z2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_48g5cNtyEfCjh-E5DQ7z2A" target="_ZoPx4NqZEfCTLpLxFP_pPQ" source="_1s1RYNtyEfCjh-E5DQ7z2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_48g5cdtyEfCjh-E5DQ7z2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_48g5cttyEfCjh-E5DQ7z2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_OYOoANsOEfCThLbEgJRfFQ" name="Customer" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_PYWoQNsOEfCThLbEgJRfFQ" name="CSO"/>
      <actors xmi:type="process:Actor" xmi:id="_P-0LUNsOEfCThLbEgJRfFQ" name="CMO"/>
      <actors xmi:type="process:Actor" xmi:id="_RuKpENsOEfCThLbEgJRfFQ" name="Audit Department"/>
      <actors xmi:type="process:Actor" xmi:id="_TOo9UNsOEfCThLbEgJRfFQ" name="Department"/>
      <actors xmi:type="process:Actor" xmi:id="_pQdlYNt0EfCjh-E5DQ7z2A" name="SQD"/>
      <contract xmi:type="process:Contract" xmi:id="_eWEmrNEPEfCon65KSlHj9Q"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eWEmrdEPEfCon65KSlHj9Q">
        <name xmi:type="expression:Expression" xmi:id="_eWEmrtEPEfCon65KSlHj9Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eWEmr9EPEfCon65KSlHj9Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eWEmsNEPEfCon65KSlHj9Q">
        <name xmi:type="expression:Expression" xmi:id="_eWEmsdEPEfCon65KSlHj9Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eWEmstEPEfCon65KSlHj9Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eWEms9EPEfCon65KSlHj9Q">
        <name xmi:type="expression:Expression" xmi:id="_eWEmtNEPEfCon65KSlHj9Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eWEmtdEPEfCon65KSlHj9Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eWEmttEPEfCon65KSlHj9Q">
        <name xmi:type="expression:Expression" xmi:id="_eWEmt9EPEfCon65KSlHj9Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eWEmuNEPEfCon65KSlHj9Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eWEmudEPEfCon65KSlHj9Q">
        <name xmi:type="expression:Expression" xmi:id="_eWEmutEPEfCon65KSlHj9Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eWEmu9EPEfCon65KSlHj9Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_eWEmvNEPEfCon65KSlHj9Q" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_eWEmvdEPEfCon65KSlHj9Q" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_eWEmvtEPEfCon65KSlHj9Q" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_eWEmv9EPEfCon65KSlHj9Q" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_eWEmwNEPEfCon65KSlHj9Q" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_eWEmwdEPEfCon65KSlHj9Q" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_eWEmwtEPEfCon65KSlHj9Q" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_eWEmw9EPEfCon65KSlHj9Q" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_eWEmxNEPEfCon65KSlHj9Q" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_eWEmxdEPEfCon65KSlHj9Q" type="Process" element="_eWEmkNEPEfCon65KSlHj9Q" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_eWEmxtEPEfCon65KSlHj9Q" type="2007" element="_eWEmkdEPEfCon65KSlHj9Q">
      <children xmi:type="notation:DecorationNode" xmi:id="_eWEmx9EPEfCon65KSlHj9Q" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_eWEmyNEPEfCon65KSlHj9Q" type="7001">
        <children xmi:type="notation:Node" xmi:id="_eWEmydEPEfCon65KSlHj9Q" type="3007" element="_eWEmktEPEfCon65KSlHj9Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_eWEmytEPEfCon65KSlHj9Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eWEmy9EPEfCon65KSlHj9Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_X5xScNHIEfCq4fAUiiAMQg" type="3027" element="_X5vdQNHIEfCq4fAUiiAMQg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_X5ygkNHIEfCq4fAUiiAMQg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_X5xScdHIEfCq4fAUiiAMQg" x="685" y="56" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-_yEoNHIEfCq4fAUiiAMQg" type="3003" element="_-_xdkNHIEfCq4fAUiiAMQg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_-_yEotHIEfCq4fAUiiAMQg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_-_yEo9HIEfCq4fAUiiAMQg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-_yEodHIEfCq4fAUiiAMQg" x="2037" y="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eWEmz9EPEfCon65KSlHj9Q" type="3002" element="_eWEmk9EPEfCon65KSlHj9Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_eWEm0NEPEfCon65KSlHj9Q" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_eWEm0dEPEfCon65KSlHj9Q" x="9" y="12"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eWEm0tEPEfCon65KSlHj9Q" x="50" y="121"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZN3qSdmtEfCuLry7pRqKVA" type="3027" element="_ZN3qQNmtEfCuLry7pRqKVA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZN3qS9mtEfCuLry7pRqKVA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZN3qStmtEfCuLry7pRqKVA" x="301" y="94" width="162" height="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nUqhgNs8EfC71cxg3o_nxQ" type="3005" element="_nUoFQNs8EfC71cxg3o_nxQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nUrIkNs8EfC71cxg3o_nxQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nUqhgds8EfC71cxg3o_nxQ" x="141" y="103" width="125" height="62"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eWEm09EPEfCon65KSlHj9Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eWEm1NEPEfCon65KSlHj9Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eWEm1dEPEfCon65KSlHj9Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eWEm1tEPEfCon65KSlHj9Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eWEm19EPEfCon65KSlHj9Q" x="58" y="10" width="2187" height="316"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_zToloNEPEfCon65KSlHj9Q" type="3007" element="_zTnXgNEPEfCon65KSlHj9Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_zTpMsNEPEfCon65KSlHj9Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_zTpMsdEPEfCon65KSlHj9Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_MU6IINHIEfCq4fAUiiAMQg" type="3008" element="_MU3E0NHIEfCq4fAUiiAMQg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_MU6vMNHIEfCq4fAUiiAMQg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_MU7WQNHIEfCq4fAUiiAMQg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MU6IIdHIEfCq4fAUiiAMQg" x="581" y="102" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PceHYNUoEfCluqGJMweO3w" type="3005" element="_PccSMNUoEfCluqGJMweO3w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PceucNUoEfCluqGJMweO3w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PceHYdUoEfCluqGJMweO3w" x="329" y="89" width="141" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wJilnNs-EfC71cxg3o_nxQ" type="3005" element="_wJh-gNs-EfC71cxg3o_nxQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wJjMoNs-EfC71cxg3o_nxQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wJilnds-EfC71cxg3o_nxQ" x="841" y="90" width="150" height="75"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_zTolodEPEfCon65KSlHj9Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_zTolotEPEfCon65KSlHj9Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_zTolo9EPEfCon65KSlHj9Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_zTpMstEPEfCon65KSlHj9Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zTolpNEPEfCon65KSlHj9Q" x="58" y="280" width="2187" height="312"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_j18TINEQEfCon65KSlHj9Q" type="3007" element="_j17sENEQEfCon65KSlHj9Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_j186MNEQEfCon65KSlHj9Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_j186MdEQEfCon65KSlHj9Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_VcEPANHKEfCq4fAUiiAMQg" type="3005" element="_VcDA4NHKEfCq4fAUiiAMQg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VcEPAtHKEfCq4fAUiiAMQg" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_2qsp4NqYEfCTLpLxFP_pPQ" type="3043" element="_2qrbwNqYEfCTLpLxFP_pPQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_2qsp4tqYEfCTLpLxFP_pPQ" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_2qsp49qYEfCTLpLxFP_pPQ" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2qsp4dqYEfCTLpLxFP_pPQ"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VcEPAdHKEfCq4fAUiiAMQg" x="189" y="73" width="181" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__Wq7iNqYEfCTLpLxFP_pPQ" type="3027" element="__WqUcNqYEfCTLpLxFP_pPQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__Wq7itqYEfCTLpLxFP_pPQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__Wq7idqYEfCTLpLxFP_pPQ" x="1158" y="173" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IujQ4NqZEfCTLpLxFP_pPQ" type="3003" element="_IuiCwNqZEfCTLpLxFP_pPQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IujQ4tqZEfCTLpLxFP_pPQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IujQ49qZEfCTLpLxFP_pPQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IujQ4dqZEfCTLpLxFP_pPQ" x="1430" y="181"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_j18TIdEQEfCon65KSlHj9Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_j18TItEQEfCon65KSlHj9Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_j18TI9EQEfCon65KSlHj9Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_j186MtEQEfCon65KSlHj9Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_j18TJNEQEfCon65KSlHj9Q" x="58" y="975" width="2337" height="317"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_kZVUENEQEfCon65KSlHj9Q" type="3007" element="_kZUF8NEQEfCon65KSlHj9Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_kZVUFdEQEfCon65KSlHj9Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_kZVUFtEQEfCon65KSlHj9Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_f27-ENmvEfCuLry7pRqKVA" type="3008" element="_f26I4NmvEfCuLry7pRqKVA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_f27-EtmvEfCuLry7pRqKVA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_f27-E9mvEfCuLry7pRqKVA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f27-EdmvEfCuLry7pRqKVA" x="469" y="72" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tv2ZNtmwEfCuLry7pRqKVA" type="3027" element="_tv0kANmwEfCuLry7pRqKVA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tv2ZONmwEfCuLry7pRqKVA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tv2ZN9mwEfCuLry7pRqKVA" x="625" y="65" width="204" height="102"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eEmd4NqYEfCTLpLxFP_pPQ" type="3027" element="_eEiMcNqYEfCTLpLxFP_pPQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eEnE8NqYEfCTLpLxFP_pPQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eEmd4dqYEfCTLpLxFP_pPQ" x="1131" y="201" width="153" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rxZlENqYEfCTLpLxFP_pPQ" type="3003" element="_rxXv4NqYEfCTLpLxFP_pPQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_rxZlEtqYEfCTLpLxFP_pPQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_rxaMINqYEfCTLpLxFP_pPQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rxZlEdqYEfCTLpLxFP_pPQ" x="1434" y="212"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pnGr_NtBEfC71cxg3o_nxQ" type="3005" element="_pnGE4NtBEfC71cxg3o_nxQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pnHTANtBEfC71cxg3o_nxQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_rlhgcNtBEfC71cxg3o_nxQ" type="3043" element="_rlfrQNtBEfC71cxg3o_nxQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_rlhgcttBEfC71cxg3o_nxQ" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_rlhgc9tBEfC71cxg3o_nxQ" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rlhgcdtBEfC71cxg3o_nxQ"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pnGr_dtBEfC71cxg3o_nxQ" x="79" y="67" width="189" height="94"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_kZVUEdEQEfCon65KSlHj9Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_kZVUEtEQEfCon65KSlHj9Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_kZVUE9EQEfCon65KSlHj9Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_kZVUF9EQEfCon65KSlHj9Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kZVUFNEQEfCon65KSlHj9Q" x="58" y="628" width="2337" height="347"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_krTPgNmwEfCuLry7pRqKVA" type="3007" element="_krRaUNmwEfCuLry7pRqKVA">
          <children xmi:type="notation:DecorationNode" xmi:id="_krTPhdmwEfCuLry7pRqKVA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_krTPhtmwEfCuLry7pRqKVA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PotKA9mxEfCuLry7pRqKVA" type="3008" element="_Por74NmxEfCuLry7pRqKVA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PotKBdmxEfCuLry7pRqKVA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PotKBtmxEfCuLry7pRqKVA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PotKBNmxEfCuLry7pRqKVA" x="409" y="118" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_02fZ2dmyEfCuLry7pRqKVA" type="3027" element="_02fZ0NmyEfCuLry7pRqKVA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_02fZ29myEfCuLry7pRqKVA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_02fZ2tmyEfCuLry7pRqKVA" x="936" y="161" width="156" height="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZoQY-NqZEfCTLpLxFP_pPQ" type="3027" element="_ZoPx4NqZEfCTLpLxFP_pPQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZoRAANqZEfCTLpLxFP_pPQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZoQY-dqZEfCTLpLxFP_pPQ" x="1249" y="254" width="161" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ci92kNqZEfCTLpLxFP_pPQ" type="3003" element="_ci9PgNqZEfCTLpLxFP_pPQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ci92ktqZEfCTLpLxFP_pPQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ci92k9qZEfCTLpLxFP_pPQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ci92kdqZEfCTLpLxFP_pPQ" x="1521" y="268"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qX-R8NtyEfCjh-E5DQ7z2A" type="3005" element="_qX8cwNtyEfCjh-E5DQ7z2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qX-5ANtyEfCjh-E5DQ7z2A" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_1s2fgNtyEfCjh-E5DQ7z2A" type="3043" element="_1s1RYNtyEfCjh-E5DQ7z2A" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_1s2fgttyEfCjh-E5DQ7z2A" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_1s2fg9tyEfCjh-E5DQ7z2A" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1s2fgdtyEfCjh-E5DQ7z2A"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qX-R8dtyEfCjh-E5DQ7z2A" x="149" y="110" width="165" height="82"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_krTPgdmwEfCuLry7pRqKVA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_krTPgtmwEfCuLry7pRqKVA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_krTPg9mwEfCuLry7pRqKVA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_krTPh9mwEfCuLry7pRqKVA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_krTPhNmwEfCuLry7pRqKVA" x="58" y="1292" width="2337" height="403"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_DndPQNsdEfCThLbEgJRfFQ" type="3007" element="_DmUm0NsdEfCThLbEgJRfFQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_Dnd2UNsdEfCThLbEgJRfFQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Dnd2UdsdEfCThLbEgJRfFQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_znKf-NmyEfCuLry7pRqKVA" type="3027" element="_znJ44NmyEfCuLry7pRqKVA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_znLHAdmyEfCuLry7pRqKVA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_znLHANmyEfCuLry7pRqKVA" x="581" y="123" width="164" height="82"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_DndPQdsdEfCThLbEgJRfFQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_DndPQtsdEfCThLbEgJRfFQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_DndPQ9sdEfCThLbEgJRfFQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Dnd2UtsdEfCThLbEgJRfFQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DndPRNsdEfCThLbEgJRfFQ" x="58" y="1695" width="2337" height="300"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_eWEm2NEPEfCon65KSlHj9Q"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_eWEm2dEPEfCon65KSlHj9Q" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_eWEm2tEPEfCon65KSlHj9Q"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_eWEm29EPEfCon65KSlHj9Q"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eWEm3NEPEfCon65KSlHj9Q" width="2370" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_eWEm3dEPEfCon65KSlHj9Q"/>
    <edges xmi:type="notation:Connector" xmi:id="_sbqMsNHJEfCq4fAUiiAMQg" type="4001" element="_sbo-kNHJEfCq4fAUiiAMQg" source="_MU6IINHIEfCq4fAUiiAMQg" target="_X5xScNHIEfCq4fAUiiAMQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sbqMs9HJEfCq4fAUiiAMQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sbqzwNHJEfCq4fAUiiAMQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sbqMsdHJEfCq4fAUiiAMQg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sbqMstHJEfCq4fAUiiAMQg" points="[-23, -28, -149, 609]$[-23, -361, -149, 276]$[117, -361, -9, 276]$[117, -628, -9, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_sbso8NHJEfCq4fAUiiAMQg" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_34QZsNUoEfCluqGJMweO3w" id="(0.52,0.86)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E8I8MNUoEfCluqGJMweO3w" type="4001" element="_E8HHANUoEfCluqGJMweO3w" source="_ZN3qSdmtEfCuLry7pRqKVA" target="_PceHYNUoEfCluqGJMweO3w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E8JjQNUoEfCluqGJMweO3w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E8JjQdUoEfCluqGJMweO3w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E8I8MdUoEfCluqGJMweO3w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E8I8MtUoEfCluqGJMweO3w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YdYHMNUoEfCluqGJMweO3w" type="4001" element="_YdW5ENUoEfCluqGJMweO3w" source="_PceHYNUoEfCluqGJMweO3w" target="_MU6IINHIEfCq4fAUiiAMQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YdYHM9UoEfCluqGJMweO3w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YdYHNNUoEfCluqGJMweO3w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YdYHMdUoEfCluqGJMweO3w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YdYHMtUoEfCluqGJMweO3w" points="[0, 4, -116, 10]$[112, 4, -4, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_YdajcNUoEfCluqGJMweO3w" id="(1.0,0.4142857142857143)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_YdajcdUoEfCluqGJMweO3w" id="(0.11627906976744186,0.23255813953488372)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Z3rU4NmwEfCuLry7pRqKVA" type="4001" element="_Z3pfsNmwEfCuLry7pRqKVA" source="_f27-ENmvEfCuLry7pRqKVA" target="_VcEPANHKEfCq4fAUiiAMQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Z3rU49mwEfCuLry7pRqKVA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Z3r78NmwEfCuLry7pRqKVA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Z3rU4dmwEfCuLry7pRqKVA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Z3rU4tmwEfCuLry7pRqKVA" points="[-24, 2, 98, -191]$[-189, 165, -67, -28]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Z3vmUNmwEfCuLry7pRqKVA" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tv2ZPNmwEfCuLry7pRqKVA" type="4001" element="_tv2ZOdmwEfCuLry7pRqKVA" source="_f27-ENmvEfCuLry7pRqKVA" target="_tv2ZNtmwEfCuLry7pRqKVA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tv2ZP9mwEfCuLry7pRqKVA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tv2ZQNmwEfCuLry7pRqKVA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tv2ZPdmwEfCuLry7pRqKVA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tv2ZPtmwEfCuLry7pRqKVA" points="[19, -2, -218, -10]$[135, -2, -102, -10]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_znLuENmyEfCuLry7pRqKVA" type="4001" element="_znLHAtmyEfCuLry7pRqKVA" source="_PotKA9mxEfCuLry7pRqKVA" target="_znKf-NmyEfCuLry7pRqKVA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_znLuE9myEfCuLry7pRqKVA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_znLuFNmyEfCuLry7pRqKVA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_znLuEdmyEfCuLry7pRqKVA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_znLuEtmyEfCuLry7pRqKVA" points="[7, 15, -226, -413]$[7, 415, -226, -13]$[11, 415, -222, -13]$[11, 429, -222, 1]$[151, 429, -82, 1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_02fZ39myEfCuLry7pRqKVA" type="4001" element="_02fZ3NmyEfCuLry7pRqKVA" source="_PotKA9mxEfCuLry7pRqKVA" target="_02fZ2dmyEfCuLry7pRqKVA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_02fZ4tmyEfCuLry7pRqKVA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_02fZ49myEfCuLry7pRqKVA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_02fZ4NmyEfCuLry7pRqKVA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_02fZ4dmyEfCuLry7pRqKVA" points="[28, -8, -568, -66]$[596, -8, 0, -66]$[596, 19, 0, -39]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UcfesNqZEfCTLpLxFP_pPQ" id="(0.20930232558139536,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gkE0EtmzEfCuLry7pRqKVA" type="4001" element="_gkENANmzEfCuLry7pRqKVA" source="_znKf-NmyEfCuLry7pRqKVA" target="_-_yEoNHIEfCq4fAUiiAMQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gkE0FdmzEfCuLry7pRqKVA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gkE0FtmzEfCuLry7pRqKVA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gkE0E9mzEfCuLry7pRqKVA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gkE0FNmzEfCuLry7pRqKVA" points="[0, 0, -946, 1278]$[997, 0, 51, 1278]$[997, -1274, 51, 4]$[969, -1274, 23, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gkE0F9mzEfCuLry7pRqKVA" id="(1.0,0.35365853658536583)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gkE0GNmzEfCuLry7pRqKVA" id="(0.16666666666666666,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hZ1XYNmzEfCuLry7pRqKVA" type="4001" element="_hZ0JQNmzEfCuLry7pRqKVA" source="_02fZ2dmyEfCuLry7pRqKVA" target="_-_yEoNHIEfCq4fAUiiAMQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hZ1XY9mzEfCuLry7pRqKVA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hZ1XZNmzEfCuLry7pRqKVA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hZ1XYdmzEfCuLry7pRqKVA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hZ1XYtmzEfCuLry7pRqKVA" points="[0, 0, -720, 598]$[720, -588, 0, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hZ2lgNmzEfCuLry7pRqKVA" id="(1.0,0.4230769230769231)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mMJCMNqXEfCTLpLxFP_pPQ" type="4001" element="_mL1gMNqXEfCTLpLxFP_pPQ" source="_X5xScNHIEfCq4fAUiiAMQg" target="_-_yEoNHIEfCq4fAUiiAMQg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mMJpQNqXEfCTLpLxFP_pPQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mMKQUNqXEfCTLpLxFP_pPQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mMJCMdqXEfCTLpLxFP_pPQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mMJCMtqXEfCTLpLxFP_pPQ" points="[0, -2, -931, 0]$[928, 9, -3, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mMV2gNqXEfCTLpLxFP_pPQ" id="(1.0,0.3968253968253968)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rxazMdqYEfCTLpLxFP_pPQ" type="4001" element="_rxaMIdqYEfCTLpLxFP_pPQ" source="_eEmd4NqYEfCTLpLxFP_pPQ" target="_rxZlENqYEfCTLpLxFP_pPQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rxazNNqYEfCTLpLxFP_pPQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rxazNdqYEfCTLpLxFP_pPQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rxazMtqYEfCTLpLxFP_pPQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rxazM9qYEfCTLpLxFP_pPQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__WsJo9qYEfCTLpLxFP_pPQ" type="4001" element="__WsJoNqYEfCTLpLxFP_pPQ" source="_2qsp4NqYEfCTLpLxFP_pPQ" target="__Wq7iNqYEfCTLpLxFP_pPQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__WswsNqYEfCTLpLxFP_pPQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__WswsdqYEfCTLpLxFP_pPQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__WsJpNqYEfCTLpLxFP_pPQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__WsJpdqYEfCTLpLxFP_pPQ" points="[0, 13, -977, 12]$[0, 24, -977, 23]$[927, 24, -50, 23]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yu9XoNqZEfCTLpLxFP_pPQ" id="(0.16,0.64)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Iuj389qZEfCTLpLxFP_pPQ" type="4001" element="_Iuj38NqZEfCTLpLxFP_pPQ" source="__Wq7iNqYEfCTLpLxFP_pPQ" target="_IujQ4NqZEfCTLpLxFP_pPQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Iuj39tqZEfCTLpLxFP_pPQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Iuj399qZEfCTLpLxFP_pPQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Iuj39NqZEfCTLpLxFP_pPQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Iuj39dqZEfCTLpLxFP_pPQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ci-dotqZEfCTLpLxFP_pPQ" type="4001" element="_ci92lNqZEfCTLpLxFP_pPQ" source="_ZoQY-NqZEfCTLpLxFP_pPQ" target="_ci92kNqZEfCTLpLxFP_pPQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ci-dpdqZEfCTLpLxFP_pPQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ci-dptqZEfCTLpLxFP_pPQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ci-do9qZEfCTLpLxFP_pPQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ci-dpNqZEfCTLpLxFP_pPQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kqjEoNs8EfC71cxg3o_nxQ" type="4001" element="_kqh2gNs8EfC71cxg3o_nxQ" source="_eWEmz9EPEfCon65KSlHj9Q" target="_nUqhgNs8EfC71cxg3o_nxQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kqjrsNs8EfC71cxg3o_nxQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kqjrsds8EfC71cxg3o_nxQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kqjEods8EfC71cxg3o_nxQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kqjEots8EfC71cxg3o_nxQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nuyRsNs8EfC71cxg3o_nxQ" type="4001" element="_nuvOYNs8EfC71cxg3o_nxQ" source="_nUqhgNs8EfC71cxg3o_nxQ" target="_ZN3qSdmtEfCuLry7pRqKVA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nuy4wNs8EfC71cxg3o_nxQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nuy4wds8EfC71cxg3o_nxQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nuyRsds8EfC71cxg3o_nxQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nuyRsts8EfC71cxg3o_nxQ" points="[0, 1, -30, 1]$[31, -28, 1, -28]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nu18ENs8EfC71cxg3o_nxQ" id="(1.0,0.46774193548387094)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nu18Eds8EfC71cxg3o_nxQ" id="(0.030864197530864196,0.4634146341463415)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vyKAUts-EfC71cxg3o_nxQ" type="4001" element="_vyJZQNs-EfC71cxg3o_nxQ" source="_MU6IINHIEfCq4fAUiiAMQg" target="_wJilnNs-EfC71cxg3o_nxQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vyKnYNs-EfC71cxg3o_nxQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vyKnYds-EfC71cxg3o_nxQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vyKAU9s-EfC71cxg3o_nxQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vyKAVNs-EfC71cxg3o_nxQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ly9E49tBEfC71cxg3o_nxQ" type="4001" element="_ly9E4NtBEfC71cxg3o_nxQ" source="_wJilnNs-EfC71cxg3o_nxQ" target="_pnGr_NtBEfC71cxg3o_nxQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ly9E5ttBEfC71cxg3o_nxQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ly9E59tBEfC71cxg3o_nxQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ly9E5NtBEfC71cxg3o_nxQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ly9E5dtBEfC71cxg3o_nxQ" points="[0, 38, 741, -262]$[0, 115, 741, -185]$[-741, 115, 0, -185]$[-741, 253, 0, -47]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tXIoANtBEfC71cxg3o_nxQ" type="4001" element="_tXHZ4NtBEfC71cxg3o_nxQ" source="_rlhgcNtBEfC71cxg3o_nxQ" target="_eEmd4NqYEfCTLpLxFP_pPQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tXJPENtBEfC71cxg3o_nxQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tXJPEdtBEfC71cxg3o_nxQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tXIoAdtBEfC71cxg3o_nxQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tXIoAttBEfC71cxg3o_nxQ" points="[0, 0, -804, -45]$[747, 44, -57, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tXM5cNtBEfC71cxg3o_nxQ" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3YByQNtOEfCjh-E5DQ7z2A" type="4001" element="_3WRewNtOEfCjh-E5DQ7z2A" source="_pnGr_NtBEfC71cxg3o_nxQ" target="_f27-ENmvEfCuLry7pRqKVA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3YDncNtOEfCjh-E5DQ7z2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3YDncdtOEfCjh-E5DQ7z2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3YCZUNtOEfCjh-E5DQ7z2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3YCZUdtOEfCjh-E5DQ7z2A" points="[0, -1, -167, -2]$[165, -13, -2, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3YIf8NtOEfCjh-E5DQ7z2A" id="(1.0,0.26595744680851063)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lf03QttyEfCjh-E5DQ7z2A" type="4001" element="_lf0QMdtyEfCjh-E5DQ7z2A" source="_VcEPANHKEfCq4fAUiiAMQg" target="_qX-R8NtyEfCjh-E5DQ7z2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lf03RdtyEfCjh-E5DQ7z2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lf03RttyEfCjh-E5DQ7z2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lf03Q9tyEfCjh-E5DQ7z2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lf03RNtyEfCjh-E5DQ7z2A" points="[-90, 0, -42, -350]$[-174, 0, -126, -350]$[-174, 350, -126, 0]$[-130, 350, -82, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rAHQANtyEfCjh-E5DQ7z2A" type="4001" element="_rAGB4NtyEfCjh-E5DQ7z2A" source="_qX-R8NtyEfCjh-E5DQ7z2A" target="_PotKA9mxEfCuLry7pRqKVA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rAHQA9tyEfCjh-E5DQ7z2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rAHQBNtyEfCjh-E5DQ7z2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rAHQAdtyEfCjh-E5DQ7z2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rAHQAttyEfCjh-E5DQ7z2A" points="[0, -5, -88, -3]$[82, -13, -6, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rAJFMNtyEfCjh-E5DQ7z2A" id="(1.0,0.3902439024390244)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tAd-MNtyEfCjh-E5DQ7z2A" type="4001" element="_tAcwENtyEfCjh-E5DQ7z2A" source="_tv2ZNtmwEfCuLry7pRqKVA" target="_qX-R8NtyEfCjh-E5DQ7z2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tAd-M9tyEfCjh-E5DQ7z2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tAd-NNtyEfCjh-E5DQ7z2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tAd-MdtyEfCjh-E5DQ7z2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tAd-MttyEfCjh-E5DQ7z2A" points="[-57, 72, 483, -616]$[-57, 535, 483, -153]$[-416, 535, 124, -153]$[-416, 647, 124, -41]$[-598, 647, -58, -41]$[-598, 679, -58, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tAfzYNtyEfCjh-E5DQ7z2A" id="(1.0,0.29411764705882354)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tAfzYdtyEfCjh-E5DQ7z2A" id="(0.8484848484848485,0.10975609756097561)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_48iHkNtyEfCjh-E5DQ7z2A" type="4001" element="_48g5cNtyEfCjh-E5DQ7z2A" source="_1s2fgNtyEfCjh-E5DQ7z2A" target="_ZoQY-NqZEfCTLpLxFP_pPQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_48iHk9tyEfCjh-E5DQ7z2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_48iHlNtyEfCjh-E5DQ7z2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_48iHkdtyEfCjh-E5DQ7z2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_48iHkttyEfCjh-E5DQ7z2A" points="[0, 0, -1128, -85]$[0, 87, -1128, 2]$[1048, 87, -80, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_48j8wNtyEfCjh-E5DQ7z2A" id="(1.0,1.0)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
